// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogDocumentDataSlicesSlice = BlogContentSlice;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

type HomeDocumentDataSlicesSlice =
  | LogoListSlice
  | GridFeatureCollectionSlice
  | CardCarouselSlice
  | CategoryGridSlice
  | SideTitleContentSlice
  | HeroCtaLeftSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = BlogDocument | HomeDocument;

/**
 * Item in *BlogContent → Default → Primary → Otros blogs*
 */
export interface BlogContentSliceDefaultPrimaryOtrosBlogsItem {
  /**
   * blog field in *BlogContent → Default → Primary → Otros blogs*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.otros_blogs[].blog
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  blog: prismic.ContentRelationshipField<"blog">;
}

/**
 * Primary content in *BlogContent → Default → Primary*
 */
export interface BlogContentSliceDefaultPrimary {
  /**
   * Portada field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.portada
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  portada: prismic.ImageField<never>;

  /**
   * Titulo field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titulo: prismic.RichTextField;

  /**
   * Bajada field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.bajada
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bajada: prismic.RichTextField;

  /**
   * Cuerpo de la noticia field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.cuerpo_de_la_noticia
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  cuerpo_de_la_noticia: prismic.RichTextField;

  /**
   * Otros blogs field in *BlogContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_content.default.primary.otros_blogs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  otros_blogs: prismic.GroupField<
    Simplify<BlogContentSliceDefaultPrimaryOtrosBlogsItem>
  >;
}

/**
 * Default variation for BlogContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogContent*
 */
type BlogContentSliceVariation = BlogContentSliceDefault;

/**
 * BlogContent Shared Slice
 *
 * - **API ID**: `blog_content`
 * - **Description**: BlogContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogContentSlice = prismic.SharedSlice<
  "blog_content",
  BlogContentSliceVariation
>;

/**
 * Item in *CardCarousel → Default → Primary → Cards*
 */
export interface CardCarouselSliceDefaultPrimaryCardsItem {
  /**
   * Card content field in *CardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_carousel.default.primary.cards[].content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * reviewer field in *CardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_carousel.default.primary.cards[].reviewer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  reviewer: prismic.RichTextField;

  /**
   * profesion field in *CardCarousel → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_carousel.default.primary.cards[].profesion
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  profesion: prismic.RichTextField;
}

/**
 * Primary content in *CardCarousel → Default → Primary*
 */
export interface CardCarouselSliceDefaultPrimary {
  /**
   * Section title field in *CardCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Cards field in *CardCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: card_carousel.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<CardCarouselSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for CardCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Heading with a group of cards below, suitable for use cases like reviews or highlights.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CardCarousel*
 */
type CardCarouselSliceVariation = CardCarouselSliceDefault;

/**
 * CardCarousel Shared Slice
 *
 * - **API ID**: `card_carousel`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardCarouselSlice = prismic.SharedSlice<
  "card_carousel",
  CardCarouselSliceVariation
>;

/**
 * Item in *CategoryGrid → Default → Primary → Items*
 */
export interface CategoryGridSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * thumbnail1 field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].thumbnail1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail1: prismic.ImageField<never>;

  /**
   * thumbnail2 field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].thumbnail2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail2: prismic.ImageField<never>;

  /**
   * thumbnail3 field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].thumbnail3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail3: prismic.ImageField<never>;

  /**
   * thumbnail4 field in *CategoryGrid → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[].thumbnail4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  thumbnail4: prismic.ImageField<never>;
}

/**
 * Primary content in *CategoryGrid → Default → Primary*
 */
export interface CategoryGridSliceDefaultPrimary {
  /**
   * Section Title field in *CategoryGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Items field in *CategoryGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: category_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<CategoryGridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for CategoryGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: A simple grid layout with image, title, and optional description overlay.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CategoryGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CategoryGrid*
 */
type CategoryGridSliceVariation = CategoryGridSliceDefault;

/**
 * CategoryGrid Shared Slice
 *
 * - **API ID**: `category_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CategoryGridSlice = prismic.SharedSlice<
  "category_grid",
  CategoryGridSliceVariation
>;

/**
 * Item in *GridFeatureCollection → Default → Primary → Items*
 */
export interface GridFeatureCollectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *GridFeatureCollection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Item Title field in *GridFeatureCollection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *GridFeatureCollection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_description: prismic.KeyTextField;

  /**
   * Item Link field in *GridFeatureCollection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.items[].item_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *GridFeatureCollection → Default → Primary*
 */
export interface GridFeatureCollectionSliceDefaultPrimary {
  /**
   * Title field in *GridFeatureCollection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Items field in *GridFeatureCollection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<GridFeatureCollectionSliceDefaultPrimaryItemsItem>
  >;

  /**
   * Description field in *GridFeatureCollection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: grid_feature_collection.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for GridFeatureCollection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Grid variation presenting multiple items side-by-side with heading and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridFeatureCollectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GridFeatureCollectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GridFeatureCollection*
 */
type GridFeatureCollectionSliceVariation = GridFeatureCollectionSliceDefault;

/**
 * GridFeatureCollection Shared Slice
 *
 * - **API ID**: `grid_feature_collection`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GridFeatureCollectionSlice = prismic.SharedSlice<
  "grid_feature_collection",
  GridFeatureCollectionSliceVariation
>;

/**
 * Primary content in *HeroCtaLeft → Default → Primary*
 */
export interface HeroCtaLeftSliceDefaultPrimary {
  /**
   * Title field in *HeroCtaLeft → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta_left.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *HeroCtaLeft → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta_left.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Description field in *HeroCtaLeft → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta_left.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA field in *HeroCtaLeft → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_cta_left.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroCtaLeft Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard hero layout with content left-aligned and one CTA button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroCtaLeftSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroCtaLeftSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroCtaLeft*
 */
type HeroCtaLeftSliceVariation = HeroCtaLeftSliceDefault;

/**
 * HeroCtaLeft Shared Slice
 *
 * - **API ID**: `hero_cta_left`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroCtaLeftSlice = prismic.SharedSlice<
  "hero_cta_left",
  HeroCtaLeftSliceVariation
>;

/**
 * Item in *LogoList → Default → Primary → Logos*
 */
export interface LogoListSliceDefaultPrimaryLogosItem {
  /**
   * Logo Image field in *LogoList → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.logos[].logo_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoList → Default → Primary*
 */
export interface LogoListSliceDefaultPrimary {
  /**
   * Title field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Logos field in *LogoList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_list.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<Simplify<LogoListSliceDefaultPrimaryLogosItem>>;
}

/**
 * Default variation for LogoList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a simple title and a repeating group of images in a row or grid.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoList*
 */
type LogoListSliceVariation = LogoListSliceDefault;

/**
 * LogoList Shared Slice
 *
 * - **API ID**: `logo_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoListSlice = prismic.SharedSlice<
  "logo_list",
  LogoListSliceVariation
>;

/**
 * Primary content in *SideTitleContent → Basic (Right Content) → Primary*
 */
export interface SideTitleContentSliceBasicRightContentPrimary {
  /**
   * Titulo field in *SideTitleContent → Basic (Right Content) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_title_content.basic_right_content.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Main Content field in *SideTitleContent → Basic (Right Content) → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_title_content.basic_right_content.primary.main_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  main_content: prismic.RichTextField;

  /**
   * Imagen de fondo field in *SideTitleContent → Basic (Right Content) → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_title_content.basic_right_content.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;
}

/**
 * Basic (Right Content) variation for SideTitleContent Slice
 *
 * - **API ID**: `basic_right_content`
 * - **Description**: Side title on the left, and a large content area to the right (can be text or other media).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideTitleContentSliceBasicRightContent =
  prismic.SharedSliceVariation<
    "basic_right_content",
    Simplify<SideTitleContentSliceBasicRightContentPrimary>,
    never
  >;

/**
 * Slice variation for *SideTitleContent*
 */
type SideTitleContentSliceVariation = SideTitleContentSliceBasicRightContent;

/**
 * SideTitleContent Shared Slice
 *
 * - **API ID**: `side_title_content`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideTitleContentSlice = prismic.SharedSlice<
  "side_title_content",
  SideTitleContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogContentSlice,
      BlogContentSliceDefaultPrimaryOtrosBlogsItem,
      BlogContentSliceDefaultPrimary,
      BlogContentSliceVariation,
      BlogContentSliceDefault,
      CardCarouselSlice,
      CardCarouselSliceDefaultPrimaryCardsItem,
      CardCarouselSliceDefaultPrimary,
      CardCarouselSliceVariation,
      CardCarouselSliceDefault,
      CategoryGridSlice,
      CategoryGridSliceDefaultPrimaryItemsItem,
      CategoryGridSliceDefaultPrimary,
      CategoryGridSliceVariation,
      CategoryGridSliceDefault,
      GridFeatureCollectionSlice,
      GridFeatureCollectionSliceDefaultPrimaryItemsItem,
      GridFeatureCollectionSliceDefaultPrimary,
      GridFeatureCollectionSliceVariation,
      GridFeatureCollectionSliceDefault,
      HeroCtaLeftSlice,
      HeroCtaLeftSliceDefaultPrimary,
      HeroCtaLeftSliceVariation,
      HeroCtaLeftSliceDefault,
      LogoListSlice,
      LogoListSliceDefaultPrimaryLogosItem,
      LogoListSliceDefaultPrimary,
      LogoListSliceVariation,
      LogoListSliceDefault,
      SideTitleContentSlice,
      SideTitleContentSliceBasicRightContentPrimary,
      SideTitleContentSliceVariation,
      SideTitleContentSliceBasicRightContent,
    };
  }
}
