// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  card_carousel: dynamic(() => import("./CardCarousel")),
  category_grid: dynamic(() => import("./CategoryGrid")),
  grid_feature_collection: dynamic(() => import("./GridFeatureCollection")),
  hero_cta_left: dynamic(() => import("./HeroCtaLeft")),
  logo_list: dynamic(() => import("./LogoList")),
  side_title_content: dynamic(() => import("./SideTitleContent")),
};
